-- =========================================================================
-- SHRI KRISHNA ENTERPRISE MANAGER - COMPLETE DATABASE INITIALIZATION SCHEMA
-- Highly secure, RLS-hardened, and optimized for Hospital & Dairy Modules.
-- Copy-paste this entire script into your Supabase SQL Editor and run it.
-- =========================================================================

BEGIN;

-- =========================================================================
-- 1. TABLE CREATION (Backwards-compatible, creates tables if missing)
-- =========================================================================

-- Hospital Entries (Patients)
CREATE TABLE IF NOT EXISTS public.hospital_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT DEFAULT 'Patient',
    name TEXT,
    father_husband TEXT,
    phone TEXT,
    pincode TEXT,
    city TEXT,
    state TEXT,
    dob TEXT,
    anniversary TEXT,
    age TEXT,
    village TEXT,
    post TEXT,
    block TEXT,
    district TEXT,
    doctor TEXT,
    department TEXT,
    photo TEXT,
    id_card TEXT,
    password TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Dairy Entries (Farmers)
CREATE TABLE IF NOT EXISTS public.dairy_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT DEFAULT 'Farmer',
    name TEXT,
    father_husband TEXT,
    phone TEXT,
    pincode TEXT,
    city TEXT,
    state TEXT,
    dob TEXT,
    anniversary TEXT,
    age TEXT,
    village TEXT,
    post TEXT,
    block TEXT,
    district TEXT,
    bmc_dpmc TEXT,
    aadhar TEXT,
    photo TEXT,
    aadhaar_card TEXT,
    password TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Staff Accounts (Shared table, scoped by module)
CREATE TABLE IF NOT EXISTS public.staff_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    name TEXT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(username, module)
);

-- Message/WhatsApp Automation Templates
CREATE TABLE IF NOT EXISTS public.templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'Custom',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Communication Logs
CREATE TABLE IF NOT EXISTS public.message_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'sent',
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- Media Library (Supports URL or Base64 file storage in 'data' column)
CREATE TABLE IF NOT EXISTS public.media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL,
    name TEXT NOT NULL,
    url TEXT,
    data TEXT, -- Base64 storage
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Institution & Dynamic Settings Configuration
CREATE TABLE IF NOT EXISTS public.settings (
    module TEXT PRIMARY KEY,
    hospital_name TEXT,
    contact_number TEXT,
    full_address TEXT,
    email_id TEXT,
    website TEXT,
    whatsapp_api_key TEXT,
    logo_url TEXT,
    auto_birthday BOOLEAN DEFAULT FALSE,
    auto_anniversary BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Location Masters (Module optional/supported for extreme customization)
CREATE TABLE IF NOT EXISTS public.state_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.district_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT,
    state TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.block_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT,
    district TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.post_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT,
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    name TEXT NOT NULL,
    pincode TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.village_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT,
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    block TEXT NOT NULL,
    name TEXT NOT NULL
);


-- =========================================================================
-- 2. SCHEMA EVOLUTION / UPDATES (Enforces correct columns on existing tables)
-- =========================================================================

-- Ensure key columns exist in entries
ALTER TABLE public.hospital_entries ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'Patient';
ALTER TABLE public.hospital_entries ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE public.hospital_entries ADD COLUMN IF NOT EXISTS bmc_dpmc TEXT;
ALTER TABLE public.hospital_entries ADD COLUMN IF NOT EXISTS aadhar TEXT;
ALTER TABLE public.hospital_entries ADD COLUMN IF NOT EXISTS aadhaar_card TEXT;

ALTER TABLE public.dairy_entries ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'Farmer';
ALTER TABLE public.dairy_entries ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE public.dairy_entries ADD COLUMN IF NOT EXISTS doctor TEXT;
ALTER TABLE public.dairy_entries ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.dairy_entries ADD COLUMN IF NOT EXISTS id_card TEXT;

-- Ensure "url" and "data" columns exist in media table for Base64 streams
ALTER TABLE public.media ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE public.media ADD COLUMN IF NOT EXISTS data TEXT;
ALTER TABLE public.media ALTER COLUMN url DROP NOT NULL;

-- Backwards-compatibility check for location master tables
ALTER TABLE public.state_master ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE public.district_master ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE public.block_master ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE public.post_master ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE public.village_master ADD COLUMN IF NOT EXISTS module TEXT;


-- =========================================================================
-- 3. SCHEMA INTEGRITY (Drop excessive NOT NULL constraints to prevent insertion failures)
-- =========================================================================

DO $$
DECLARE
    col_rec RECORD;
    managed_tables TEXT[] := ARRAY[
        'block_master', 'dairy_entries', 'district_master', 'hospital_entries', 
        'media', 'message_logs', 'post_master', 'settings', 
        'staff_accounts', 'state_master', 'templates', 'village_master'
    ];
BEGIN
    FOR col_rec IN (
        SELECT table_name, column_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = ANY(managed_tables)
        AND is_nullable = 'NO'
        AND column_name NOT IN ('id', 'created_at', 'module', 'username', 'type')
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP NOT NULL', col_rec.table_name, col_rec.column_name);
    END LOOP;
END $$;


-- =========================================================================
-- 4. ROW-LEVEL SECURITY (RLS) POLICIES MANAGEMENT (Explicit declarations for all 12 tables)
-- =========================================================================

-- First, drop any old policies on all managed tables to prevent name duplication conflicts
DROP POLICY IF EXISTS "Allow Public read" ON public.block_master;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.block_master;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.block_master;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.block_master;
DROP POLICY IF EXISTS "Public Read" ON public.block_master;
DROP POLICY IF EXISTS "Public Insert" ON public.block_master;
DROP POLICY IF EXISTS "Public Update" ON public.block_master;
DROP POLICY IF EXISTS "Public Delete" ON public.block_master;

DROP POLICY IF EXISTS "Allow Public read" ON public.dairy_entries;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.dairy_entries;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.dairy_entries;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.dairy_entries;
DROP POLICY IF EXISTS "Public Read" ON public.dairy_entries;
DROP POLICY IF EXISTS "Public Insert" ON public.dairy_entries;
DROP POLICY IF EXISTS "Public Update" ON public.dairy_entries;
DROP POLICY IF EXISTS "Public Delete" ON public.dairy_entries;

DROP POLICY IF EXISTS "Allow Public read" ON public.district_master;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.district_master;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.district_master;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.district_master;
DROP POLICY IF EXISTS "Public Read" ON public.district_master;
DROP POLICY IF EXISTS "Public Insert" ON public.district_master;
DROP POLICY IF EXISTS "Public Update" ON public.district_master;
DROP POLICY IF EXISTS "Public Delete" ON public.district_master;

DROP POLICY IF EXISTS "Allow Public read" ON public.hospital_entries;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.hospital_entries;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.hospital_entries;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.hospital_entries;
DROP POLICY IF EXISTS "Public Read" ON public.hospital_entries;
DROP POLICY IF EXISTS "Public Insert" ON public.hospital_entries;
DROP POLICY IF EXISTS "Public Update" ON public.hospital_entries;
DROP POLICY IF EXISTS "Public Delete" ON public.hospital_entries;

DROP POLICY IF EXISTS "Allow Public read" ON public.media;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.media;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.media;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.media;
DROP POLICY IF EXISTS "Public Read" ON public.media;
DROP POLICY IF EXISTS "Public Insert" ON public.media;
DROP POLICY IF EXISTS "Public Update" ON public.media;
DROP POLICY IF EXISTS "Public Delete" ON public.media;

DROP POLICY IF EXISTS "Allow Public read" ON public.message_logs;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.message_logs;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.message_logs;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.message_logs;
DROP POLICY IF EXISTS "Public Read" ON public.message_logs;
DROP POLICY IF EXISTS "Public Insert" ON public.message_logs;
DROP POLICY IF EXISTS "Public Update" ON public.message_logs;
DROP POLICY IF EXISTS "Public Delete" ON public.message_logs;

DROP POLICY IF EXISTS "Allow Public read" ON public.post_master;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.post_master;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.post_master;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.post_master;
DROP POLICY IF EXISTS "Public Read" ON public.post_master;
DROP POLICY IF EXISTS "Public Insert" ON public.post_master;
DROP POLICY IF EXISTS "Public Update" ON public.post_master;
DROP POLICY IF EXISTS "Public Delete" ON public.post_master;

DROP POLICY IF EXISTS "Allow Public read" ON public.settings;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.settings;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.settings;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.settings;
DROP POLICY IF EXISTS "Public Read" ON public.settings;
DROP POLICY IF EXISTS "Public Insert" ON public.settings;
DROP POLICY IF EXISTS "Public Update" ON public.settings;
DROP POLICY IF EXISTS "Public Delete" ON public.settings;

DROP POLICY IF EXISTS "Allow Public read" ON public.staff_accounts;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.staff_accounts;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.staff_accounts;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.staff_accounts;
DROP POLICY IF EXISTS "Public Read" ON public.staff_accounts;
DROP POLICY IF EXISTS "Public Insert" ON public.staff_accounts;
DROP POLICY IF EXISTS "Public Update" ON public.staff_accounts;
DROP POLICY IF EXISTS "Public Delete" ON public.staff_accounts;

DROP POLICY IF EXISTS "Allow Public read" ON public.state_master;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.state_master;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.state_master;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.state_master;
DROP POLICY IF EXISTS "Public Read" ON public.state_master;
DROP POLICY IF EXISTS "Public Insert" ON public.state_master;
DROP POLICY IF EXISTS "Public Update" ON public.state_master;
DROP POLICY IF EXISTS "Public Delete" ON public.state_master;

DROP POLICY IF EXISTS "Allow Public read" ON public.templates;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.templates;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.templates;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.templates;
DROP POLICY IF EXISTS "Public Read" ON public.templates;
DROP POLICY IF EXISTS "Public Insert" ON public.templates;
DROP POLICY IF EXISTS "Public Update" ON public.templates;
DROP POLICY IF EXISTS "Public Delete" ON public.templates;

DROP POLICY IF EXISTS "Allow Public read" ON public.village_master;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.village_master;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.village_master;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.village_master;
DROP POLICY IF EXISTS "Public Read" ON public.village_master;
DROP POLICY IF EXISTS "Public Insert" ON public.village_master;
DROP POLICY IF EXISTS "Public Update" ON public.village_master;
DROP POLICY IF EXISTS "Public Delete" ON public.village_master;

-- Make sure RLS is explicitly enabled on every table
ALTER TABLE public.block_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dairy_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.district_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.state_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.village_master ENABLE ROW LEVEL SECURITY;

-- 1. block_master policies
CREATE POLICY "Allow Public read" ON public.block_master FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.block_master FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.block_master FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.block_master FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 2. dairy_entries policies
CREATE POLICY "Allow Public read" ON public.dairy_entries FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.dairy_entries FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.dairy_entries FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.dairy_entries FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 3. district_master policies
CREATE POLICY "Allow Public read" ON public.district_master FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.district_master FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.district_master FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.district_master FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 4. hospital_entries policies
CREATE POLICY "Allow Public read" ON public.hospital_entries FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.hospital_entries FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.hospital_entries FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.hospital_entries FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 5. media policies
CREATE POLICY "Allow Public read" ON public.media FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.media FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.media FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.media FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 6. message_logs policies
CREATE POLICY "Allow Public read" ON public.message_logs FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.message_logs FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.message_logs FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.message_logs FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 7. post_master policies
CREATE POLICY "Allow Public read" ON public.post_master FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.post_master FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.post_master FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.post_master FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 8. settings policies
CREATE POLICY "Allow Public read" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.settings FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.settings FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.settings FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 9. staff_accounts policies
CREATE POLICY "Allow Public read" ON public.staff_accounts FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.staff_accounts FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.staff_accounts FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.staff_accounts FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 10. state_master policies
CREATE POLICY "Allow Public read" ON public.state_master FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.state_master FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.state_master FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.state_master FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 11. templates policies
CREATE POLICY "Allow Public read" ON public.templates FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.templates FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.templates FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.templates FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));

-- 12. village_master policies
CREATE POLICY "Allow Public read" ON public.village_master FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.village_master FOR INSERT WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated update" ON public.village_master FOR UPDATE USING (auth.role() IN ('anon', 'authenticated', 'service_role')) WITH CHECK (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Allow authenticated delete" ON public.village_master FOR DELETE USING (auth.role() IN ('anon', 'authenticated', 'service_role'));


-- =========================================================================
-- 5. RESOLVE DEFINDER WARNINGS
-- =========================================================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'rls_auto_enable') THEN
        REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM public;
        REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM anon;
        REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM authenticated;
    END IF;
END $$;


COMMIT;

-- Verify setup output
SELECT 'Shri Krishna Enterprise database schema successfully compiled and hardened!' as status;
